import fs from 'fs';
import path from 'path';
import {
  AIFeedbackRecord,
  AuditLog,
  Complaint,
  Department,
  InternalNote,
  StatusUpdate,
  StudentClarification,
  SystemSettings,
  User,
} from '../src/types';

const DATA_DIR = path.join(process.cwd(), '.data');
const DB_FILE = path.join(DATA_DIR, 'database.json');

export interface AppDatabase {
  users: User[];
  departments: Department[];
  complaints: Complaint[];
  auditLogs: AuditLog[];
  feedback: AIFeedbackRecord[];
  internalNotes: InternalNote[];
  statusUpdates: StatusUpdate[];
  clarifications: StudentClarification[];
  settings: SystemSettings;
}

// Initial Seed Departments
export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-hostel',
    name: 'Hostel Administration',
    code: 'HOSTEL_ADMIN',
    description: 'Manages student accommodation, room allocation, hostel facilities, and mess operations.',
    email: 'hostel.admin@university.edu',
    active: true,
    categories: ['HOSTEL', 'ACCOMMODATION', 'MESS_FOOD', 'HOSTEL_RULES'],
    staffCount: 4,
    escalationHours: 24,
    backupDepartmentId: 'dept-facilities',
    priorityHandlingRules: 'Immediate response for water/power cutoffs or living hazards.',
  },
  {
    id: 'dept-facilities',
    name: 'Facilities & Maintenance',
    code: 'FACILITIES',
    description: 'Handles campus civil, electrical, plumbing, HVAC infrastructure, and urgent physical repairs.',
    email: 'facilities@university.edu',
    active: true,
    categories: ['FACILITIES', 'ELECTRICAL', 'PLUMBING', 'CIVIL_MAINTENANCE', 'HVAC'],
    staffCount: 6,
    escalationHours: 12,
    backupDepartmentId: 'dept-security',
    priorityHandlingRules: 'Emergency protocol for exposed wiring, gas leaks, structural ceiling cracks.',
  },
  {
    id: 'dept-it',
    name: 'IT Support & Systems',
    code: 'IT_SUPPORT',
    description: 'Maintains campus Wi-Fi, computer labs, student portals, email systems, and smart classrooms.',
    email: 'itsupport@university.edu',
    active: true,
    categories: ['IT', 'WIFI_NETWORK', 'PORTAL_ACCESS', 'LAB_EQUIPMENT', 'SOFTWARE'],
    staffCount: 5,
    escalationHours: 24,
    backupDepartmentId: 'dept-general',
    priorityHandlingRules: 'High priority during online examination windows or registration deadlines.',
  },
  {
    id: 'dept-finance',
    name: 'Finance & Accounts',
    code: 'FINANCE',
    description: 'Processes tuition fees, examination payments, scholarships, refunds, and financial dues.',
    email: 'finance@university.edu',
    active: true,
    categories: ['FINANCE', 'FEE_PAYMENT', 'SCHOLARSHIP', 'REFUND', 'DUES_CLEARANCE'],
    staffCount: 3,
    escalationHours: 48,
    backupDepartmentId: 'dept-academic',
    priorityHandlingRules: 'Expedited review for double-billing before registration deadlines.',
  },
  {
    id: 'dept-academic',
    name: 'Academic Affairs',
    code: 'ACADEMIC_AFFAIRS',
    description: 'Oversees course registration, faculty coordination, curriculum, attendance disputes, and grade appeals.',
    email: 'academics@university.edu',
    active: true,
    categories: ['ACADEMICS', 'COURSE_REGISTRATION', 'FACULTY_ISSUES', 'ATTENDANCE', 'CURRICULUM'],
    staffCount: 4,
    escalationHours: 36,
    backupDepartmentId: 'dept-exam',
    priorityHandlingRules: 'Urgent handling for graduation eligibility or degree audit hurdles.',
  },
  {
    id: 'dept-exam',
    name: 'Examination Cell',
    code: 'EXAMINATION_CELL',
    description: 'Conducts end-term exams, issues hall tickets, evaluates re-checking requests, and transcripts.',
    email: 'exams@university.edu',
    active: true,
    categories: ['EXAMS', 'HALL_TICKET', 'GRADE_DISCREPANCY', 'TRANSCRIPTS', 'RE_EVALUATION'],
    staffCount: 3,
    escalationHours: 24,
    backupDepartmentId: 'dept-academic',
    priorityHandlingRules: 'Same-day resolution for missing hall tickets or schedule clashes.',
  },
  {
    id: 'dept-security',
    name: 'Campus Security & Safety',
    code: 'SECURITY',
    description: 'Guarantees campus safety, gate control, anti-ragging response, emergency management, and lost & found.',
    email: 'security@university.edu',
    active: true,
    categories: ['SAFETY', 'SECURITY', 'ANTI_RAGGING', 'THEFT', 'EMERGENCY'],
    staffCount: 8,
    escalationHours: 4,
    backupDepartmentId: 'dept-welfare',
    priorityHandlingRules: 'Immediate on-ground dispatch for threats, harassment, or safety breaches.',
  },
  {
    id: 'dept-welfare',
    name: 'Student Welfare & Counseling',
    code: 'STUDENT_WELFARE',
    description: 'Provides mental health counseling, student advocacy, disability support, and peer grievance support.',
    email: 'welfare@university.edu',
    active: true,
    categories: ['STUDENT_WELFARE', 'COUNSELING', 'DISABILITY_ACCESS', 'DISCRIMINATION_SUPPORT'],
    staffCount: 4,
    escalationHours: 12,
    backupDepartmentId: 'dept-security',
    priorityHandlingRules: 'Strict confidentiality and priority outreach for distress cases.',
  },
  {
    id: 'dept-library',
    name: 'University Library',
    code: 'LIBRARY',
    description: 'Administers book lending, digital subscriptions, study halls, and research repository access.',
    email: 'library@university.edu',
    active: true,
    categories: ['LIBRARY', 'BOOK_LENDING', 'STUDY_SPACES', 'DIGITAL_ACCESS'],
    staffCount: 3,
    escalationHours: 72,
    backupDepartmentId: 'dept-it',
    priorityHandlingRules: 'Normal processing queue.',
  },
  {
    id: 'dept-transport',
    name: 'Transport & Logistics',
    code: 'TRANSPORT',
    description: 'Manages campus shuttles, inter-campus bus routes, parking passes, and transportation schedules.',
    email: 'transport@university.edu',
    active: true,
    categories: ['TRANSPORT', 'BUS_ROUTES', 'PARKING', 'SCHEDULES'],
    staffCount: 2,
    escalationHours: 48,
    backupDepartmentId: 'dept-facilities',
    priorityHandlingRules: 'Route disruption notifications.',
  },
  {
    id: 'dept-general',
    name: 'General Administration',
    code: 'GENERAL_ADMIN',
    description: 'Coordinates general institutional inquiries, cross-departmental escalations, and registrar affairs.',
    email: 'registrar@university.edu',
    active: true,
    categories: ['GENERAL', 'ID_CARDS', 'CERTIFICATES', 'MISCELLANEOUS'],
    staffCount: 3,
    escalationHours: 48,
    backupDepartmentId: 'dept-academic',
    priorityHandlingRules: 'Triage and dispatch to respective branch.',
  },
];

// Initial Seed Users
export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-1',
    name: 'Dr. Evelyn Vance (Registrar & Admin)',
    email: 'admin@university.edu',
    role: 'ADMIN',
    active: true,
    createdAt: '2026-01-01T08:00:00.000Z',
  },
  {
    id: 'usr-staff-facilities',
    name: 'Rajesh Kumar (Facilities Head)',
    email: 'rajesh.facilities@university.edu',
    role: 'STAFF',
    departmentId: 'dept-facilities',
    active: true,
    createdAt: '2026-01-05T08:00:00.000Z',
  },
  {
    id: 'usr-staff-hostel',
    name: 'Anita Sharma (Hostel Warden & Admin)',
    email: 'anita.hostel@university.edu',
    role: 'STAFF',
    departmentId: 'dept-hostel',
    active: true,
    createdAt: '2026-01-05T08:00:00.000Z',
  },
  {
    id: 'usr-staff-it',
    name: 'David Chen (Senior Systems Engineer)',
    email: 'david.it@university.edu',
    role: 'STAFF',
    departmentId: 'dept-it',
    active: true,
    createdAt: '2026-01-05T08:00:00.000Z',
  },
  {
    id: 'usr-staff-finance',
    name: 'Priya Patel (Accounts Officer)',
    email: 'priya.finance@university.edu',
    role: 'STAFF',
    departmentId: 'dept-finance',
    active: true,
    createdAt: '2026-01-05T08:00:00.000Z',
  },
  {
    id: 'usr-staff-academic',
    name: 'Prof. Marcus Bell (Academic Coordinator)',
    email: 'marcus.academics@university.edu',
    role: 'STAFF',
    departmentId: 'dept-academic',
    active: true,
    createdAt: '2026-01-05T08:00:00.000Z',
  },
  {
    id: 'usr-student-1',
    name: 'Aarav Mehta',
    email: 'aarav.mehta@student.edu',
    role: 'STUDENT',
    studentIdNumber: 'STU-2024-8841',
    program: 'B.Tech Computer Science (3rd Year)',
    active: true,
    createdAt: '2026-02-01T09:00:00.000Z',
  },
  {
    id: 'usr-student-2',
    name: 'Rohan Deshmukh',
    email: 'rohan.d@student.edu',
    role: 'STUDENT',
    studentIdNumber: 'STU-2023-4120',
    program: 'B.Com Accounting (Final Year)',
    active: true,
    createdAt: '2026-02-01T09:00:00.000Z',
  },
  {
    id: 'usr-student-3',
    name: 'Sarah Jenkins',
    email: 'sarah.j@student.edu',
    role: 'STUDENT',
    studentIdNumber: 'STU-2025-1092',
    program: 'B.Sc Biotechnology (2nd Year)',
    active: true,
    createdAt: '2026-02-01T09:00:00.000Z',
  },
  {
    id: 'usr-student-4',
    name: 'Vikram Aditya',
    email: 'vikram.a@student.edu',
    role: 'STUDENT',
    studentIdNumber: 'STU-2024-6519',
    program: 'MBA Finance (1st Year)',
    active: true,
    createdAt: '2026-02-01T09:00:00.000Z',
  },
  {
    id: 'usr-student-5',
    name: 'Pooja Nair',
    email: 'pooja.n@student.edu',
    role: 'STUDENT',
    studentIdNumber: 'STU-2025-3310',
    program: 'B.A. Economics (1st Year)',
    active: true,
    createdAt: '2026-02-01T09:00:00.000Z',
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  confidenceThresholdHigh: 0.8,
  confidenceThresholdMedium: 0.6,
  defaultSlaHoursLow: 72,
  defaultSlaHoursMedium: 24,
  defaultSlaHoursHigh: 8,
  autoEscalationEnabled: true,
  allowedAttachmentTypes: ['image/jpeg', 'image/png', 'application/pdf', 'text/plain'],
  maxAttachmentSizeBytes: 5242880, // 5MB
  supportedLanguages: ['English', 'Hindi', 'Hinglish'],
  safetyOverrideRulesEnabled: true,
};

// Seed complaints with realistic test cases
export function generateSeedComplaints(): {
  complaints: Complaint[];
  auditLogs: AuditLog[];
  feedback: AIFeedbackRecord[];
  notes: InternalNote[];
} {
  const complaints: Complaint[] = [
    {
      id: 'cmp-1001',
      trackingNumber: 'CMP-2026-1001',
      studentId: 'usr-student-1',
      studentName: 'Aarav Mehta',
      studentEmail: 'aarav.mehta@student.edu',
      studentProgram: 'B.Tech Computer Science (3rd Year)',
      title: 'Exposed live electrical wiring in Hostel B 2nd floor hallway',
      description:
        'There is an open switchboard box with exposed sparking wires dangling at shoulder height near Room 214. Someone could accidentally brush against it and get severe electric shock.',
      campusLocation: 'North Campus - Hostel Block B',
      isOngoing: true,
      category: 'FACILITIES',
      subcategory: 'ELECTRICAL_SAFETY',
      urgency: 'HIGH',
      assignedDepartmentId: 'dept-facilities',
      assignedDepartmentName: 'Facilities & Maintenance',
      status: 'IN_PROGRESS',
      humanVerified: true,
      humanOverrideApplied: false,
      aiAnalysis: {
        id: 'ai-seed-1',
        complaintId: 'cmp-1001',
        model: 'gemini-3.7-flash',
        summary: 'Exposed live electrical wires outside Room 214 in Hostel Block B creating immediate shock hazard.',
        category: 'FACILITIES',
        subcategory: 'ELECTRICAL_SAFETY',
        urgency: 'HIGH',
        urgencyConfidence: 0.96,
        urgencyReason: 'Exposed live wiring in high-traffic student hallway poses imminent physical safety risk.',
        suggestedDepartment: 'FACILITIES',
        departmentConfidence: 0.94,
        alternativeDepartment: 'HOSTEL_ADMIN',
        riskFlags: ['POTENTIAL_SAFETY_HAZARD'],
        entities: { location: 'Hostel Block B Room 214 hallway', incidentDate: '2026-08-12' },
        detectedLanguage: 'English',
        missingInformation: [],
        requiresHumanReview: true,
        recommendedAction: 'Immediate dispatch of electrician crew and temporary cordoning.',
        processingTimeMs: 420,
        createdAt: '2026-08-12T14:10:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'HIGH',
        ruleUrgency: 'HIGH',
        finalUrgency: 'HIGH',
        ruleTriggered: true,
        triggeredRules: ['Deterministic Safety Override: Detected safety hazard keyword matching [exposed electrical wiring]'],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: true,
        routingScore: {
          primaryDept: 'dept-facilities',
          score: 95,
          explanation: 'Category FACILITIES matched with high confidence electrical hazard score.',
        },
      },
      reviewedById: 'usr-staff-facilities',
      reviewedByName: 'Rajesh Kumar',
      reviewedAt: '2026-08-12T14:25:00.000Z',
      isEscalated: false,
      createdAt: '2026-08-12T14:05:00.000Z',
      updatedAt: '2026-08-12T14:30:00.000Z',
    },
    {
      id: 'cmp-1002',
      trackingNumber: 'CMP-2026-1002',
      studentId: 'usr-student-2',
      studentName: 'Rohan Deshmukh',
      studentEmail: 'rohan.d@student.edu',
      studentProgram: 'B.Com Accounting (Final Year)',
      title: 'Tuition and Examination fee was debited twice on payment portal',
      description:
        'I attempted to pay my semester 6 exam fee of ₹4,500 on August 10th. The gateway errored out on first try but amount was deducted. Second try also deducted ₹4,500. Total ₹9,000 deducted from my bank. Reference UTR 9821481023.',
      campusLocation: 'Main Campus',
      isOngoing: true,
      category: 'FINANCE',
      subcategory: 'PAYMENT_DISCREPANCY',
      urgency: 'MEDIUM',
      assignedDepartmentId: 'dept-finance',
      assignedDepartmentName: 'Finance & Accounts',
      status: 'RESOLVED',
      humanVerified: true,
      humanOverrideApplied: false,
      aiAnalysis: {
        id: 'ai-seed-2',
        complaintId: 'cmp-1002',
        model: 'gemini-3.7-flash',
        summary: 'Student debited twice (₹4,500 x 2) for examination fee with UTR reference.',
        category: 'FINANCE',
        subcategory: 'PAYMENT_DISCREPANCY',
        urgency: 'MEDIUM',
        urgencyConfidence: 0.93,
        urgencyReason: 'Double payment deduction requires financial reconciliation and banking refund.',
        suggestedDepartment: 'FINANCE',
        departmentConfidence: 0.96,
        riskFlags: ['FINANCIAL_DISCREPANCY'],
        entities: { incidentDate: '2026-08-10', equipmentOrItem: 'Payment Portal UTR 9821481023' },
        detectedLanguage: 'English',
        missingInformation: [],
        requiresHumanReview: false,
        recommendedAction: 'Verify transaction logs with bank gateway and initiate automated refund.',
        processingTimeMs: 380,
        createdAt: '2026-08-11T09:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'MEDIUM',
        ruleUrgency: 'MEDIUM',
        finalUrgency: 'MEDIUM',
        ruleTriggered: true,
        triggeredRules: ['Operational Issue Rule: Detected financial impact keyword [charged twice]'],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: false,
        routingScore: {
          primaryDept: 'dept-finance',
          score: 96,
          explanation: 'Category FINANCE matches Finance & Accounts department.',
        },
      },
      reviewedById: 'usr-staff-finance',
      reviewedByName: 'Priya Patel',
      reviewedAt: '2026-08-11T10:15:00.000Z',
      isEscalated: false,
      studentFeedback: {
        satisfactionScore: 5,
        comment: 'Refund of ₹4,500 received in bank within 24 hours. Excellent and prompt resolution!',
        markedAsResolved: true,
        submittedAt: '2026-08-12T16:00:00.000Z',
      },
      createdAt: '2026-08-11T08:50:00.000Z',
      updatedAt: '2026-08-12T15:45:00.000Z',
      resolvedAt: '2026-08-12T15:40:00.000Z',
    },
    {
      id: 'cmp-1003',
      trackingNumber: 'CMP-2026-1003',
      studentId: 'usr-student-3',
      studentName: 'Sarah Jenkins',
      studentEmail: 'sarah.j@student.edu',
      studentProgram: 'B.Sc Biotechnology (2nd Year)',
      title: 'Hostel Block C 3rd floor Wi-Fi access point down for 4 days',
      description:
        'Hostel C third floor Wi-Fi SSID "Univ-Student-5G" connects but shows "No Internet". We have ongoing lab submissions due this Friday and students are having to use cellular hotspot data.',
      campusLocation: 'South Campus - Hostel Block C',
      isOngoing: true,
      category: 'IT',
      subcategory: 'WIFI_NETWORK',
      urgency: 'MEDIUM',
      assignedDepartmentId: 'dept-it',
      assignedDepartmentName: 'IT Support & Systems',
      status: 'ASSIGNED',
      humanVerified: true,
      humanOverrideApplied: false,
      aiAnalysis: {
        id: 'ai-seed-3',
        complaintId: 'cmp-1003',
        model: 'gemini-3.7-flash',
        summary: 'Wi-Fi AP outage in Hostel C 3rd floor impacting student academic submissions.',
        category: 'IT',
        subcategory: 'WIFI_NETWORK',
        urgency: 'MEDIUM',
        urgencyConfidence: 0.91,
        urgencyReason: 'Prolonged 4-day outage impacting academic assignments approaching deadline.',
        suggestedDepartment: 'IT_SUPPORT',
        departmentConfidence: 0.95,
        alternativeDepartment: 'HOSTEL_ADMIN',
        riskFlags: ['ACADEMIC_CONSEQUENCE'],
        entities: { location: 'Hostel Block C 3rd Floor', deadline: 'Friday' },
        detectedLanguage: 'English',
        missingInformation: [],
        requiresHumanReview: false,
        recommendedAction: 'Reboot switch/access point or dispatch network technician.',
        processingTimeMs: 410,
        createdAt: '2026-08-13T11:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'MEDIUM',
        ruleUrgency: 'MEDIUM',
        finalUrgency: 'MEDIUM',
        ruleTriggered: true,
        triggeredRules: ['Operational Issue Rule: Detected network connectivity keyword [wifi]'],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: false,
        routingScore: {
          primaryDept: 'dept-it',
          score: 94,
          explanation: 'Category IT matches IT Support department with high confidence.',
        },
      },
      isEscalated: false,
      createdAt: '2026-08-13T10:45:00.000Z',
      updatedAt: '2026-08-13T11:30:00.000Z',
    },
    {
      id: 'cmp-1004',
      trackingNumber: 'CMP-2026-1004',
      studentId: 'usr-student-4',
      studentName: 'Vikram Aditya',
      studentEmail: 'vikram.a@student.edu',
      studentProgram: 'MBA Finance (1st Year)',
      title: 'Ceiling plaster peeling and dripping water above study desk in Room 104',
      description:
        'Continuous water seepage from overhead bathroom on 2nd floor is causing chunks of ceiling plaster to fall onto my study desk. Books were damaged and there is musty mold smell.',
      campusLocation: 'Hostel Block A Room 104',
      isOngoing: true,
      category: 'HOSTEL',
      subcategory: 'ROOM_MAINTENANCE',
      urgency: 'MEDIUM',
      assignedDepartmentId: 'dept-hostel',
      assignedDepartmentName: 'Hostel Administration',
      status: 'IN_PROGRESS',
      humanVerified: true,
      humanOverrideApplied: true, // Example of Human Override for model feedback demonstration
      overrideReason: 'Reassigned from Facilities to Hostel Admin for immediate student room relocation while repairs occur.',
      aiAnalysis: {
        id: 'ai-seed-4',
        complaintId: 'cmp-1004',
        model: 'gemini-3.7-flash',
        summary: 'Ceiling plaster peeling and water leakage damaging study desk in Room 104.',
        category: 'FACILITIES',
        subcategory: 'PLUMBING_CIVIL',
        urgency: 'MEDIUM',
        urgencyConfidence: 0.88,
        urgencyReason: 'Water seepage causing cosmetic and property damage to study desk.',
        suggestedDepartment: 'FACILITIES',
        departmentConfidence: 0.86,
        alternativeDepartment: 'HOSTEL_ADMIN',
        riskFlags: ['INFRASTRUCTURE_FAILURE'],
        entities: { location: 'Hostel Block A Room 104' },
        detectedLanguage: 'English',
        missingInformation: [],
        requiresHumanReview: false,
        recommendedAction: 'Inspect 2nd floor bathroom plumbing and repair ceiling.',
        processingTimeMs: 450,
        createdAt: '2026-08-12T08:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'MEDIUM',
        ruleUrgency: 'MEDIUM',
        finalUrgency: 'MEDIUM',
        ruleTriggered: true,
        triggeredRules: ['Operational Issue Rule: Detected infrastructure keyword [leaking]'],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: false,
        routingScore: {
          primaryDept: 'dept-facilities',
          score: 88,
          explanation: 'Facilities department mapped for plumbing and civil repair.',
        },
      },
      reviewedById: 'usr-staff-hostel',
      reviewedByName: 'Anita Sharma',
      reviewedAt: '2026-08-12T09:30:00.000Z',
      isEscalated: false,
      createdAt: '2026-08-12T07:45:00.000Z',
      updatedAt: '2026-08-12T09:30:00.000Z',
    },
    {
      id: 'cmp-1005',
      trackingNumber: 'CMP-2026-1005',
      studentId: 'usr-student-5',
      studentName: 'Pooja Nair',
      studentEmail: 'pooja.n@student.edu',
      studentProgram: 'B.A. Economics (1st Year)',
      title: 'Suggestion for Central Library weekend operating hours extension during mid-terms',
      description:
        'Currently the library closes at 8:00 PM on Saturdays and Sundays. Many students preparing for upcoming mid-term exams need a quiet air-conditioned space. Requesting extension until 11:00 PM.',
      campusLocation: 'Central Library',
      isOngoing: false,
      category: 'LIBRARY',
      subcategory: 'LIBRARY_SERVICES',
      urgency: 'LOW',
      assignedDepartmentId: 'dept-library',
      assignedDepartmentName: 'University Library',
      status: 'RESOLVED',
      humanVerified: true,
      humanOverrideApplied: false,
      aiAnalysis: {
        id: 'ai-seed-5',
        complaintId: 'cmp-1005',
        model: 'gemini-3.7-flash',
        summary: 'Student suggestion requesting extended weekend library operating hours during exam season.',
        category: 'LIBRARY',
        subcategory: 'LIBRARY_SERVICES',
        urgency: 'LOW',
        urgencyConfidence: 0.98,
        urgencyReason: 'Constructive institutional policy suggestion with no emergency or immediate operational breakdown.',
        suggestedDepartment: 'LIBRARY',
        departmentConfidence: 0.99,
        riskFlags: [],
        entities: { location: 'Central Library', deadline: 'Mid-term exams' },
        detectedLanguage: 'English',
        missingInformation: [],
        requiresHumanReview: false,
        recommendedAction: 'Forward to Library Committee for semester schedule review.',
        processingTimeMs: 340,
        createdAt: '2026-08-10T12:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'LOW',
        ruleUrgency: 'LOW',
        finalUrgency: 'LOW',
        ruleTriggered: false,
        triggeredRules: [],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: false,
        routingScore: {
          primaryDept: 'dept-library',
          score: 98,
          explanation: 'Library category matches Library department.',
        },
      },
      studentFeedback: {
        satisfactionScore: 4,
        comment: 'Library committee notified us that study hall will open till 10 PM on weekends. Thank you!',
        markedAsResolved: true,
        submittedAt: '2026-08-13T14:00:00.000Z',
      },
      isEscalated: false,
      createdAt: '2026-08-10T11:45:00.000Z',
      updatedAt: '2026-08-13T13:30:00.000Z',
      resolvedAt: '2026-08-13T13:30:00.000Z',
    },
    {
      id: 'cmp-1006',
      trackingNumber: 'CMP-2026-1006',
      studentId: 'usr-student-1',
      studentName: 'Aarav Mehta',
      studentEmail: 'aarav.mehta@student.edu',
      studentProgram: 'B.Tech Computer Science (3rd Year)',
      title: 'Hostel mess food quality and stale dairy served at breakfast (Hinglish)',
      description:
        'Aaj subah mess mein dahi bilkul sour thi aur bread pe mold tha. Multiple students ko mild stomach ache ho raha hai. Please inspect mess hygiene immediately.',
      campusLocation: 'Hostel Dining Hall 2',
      isOngoing: true,
      category: 'HOSTEL',
      subcategory: 'MESS_FOOD',
      urgency: 'HIGH',
      assignedDepartmentId: 'dept-hostel',
      assignedDepartmentName: 'Hostel Administration',
      status: 'REVIEW_REQUIRED',
      humanVerified: false,
      humanOverrideApplied: false,
      aiAnalysis: {
        id: 'ai-seed-6',
        complaintId: 'cmp-1006',
        model: 'gemini-3.7-flash',
        summary: 'Mess served stale yogurt and moldy bread causing mild illness among students.',
        category: 'HOSTEL',
        subcategory: 'MESS_FOOD',
        urgency: 'HIGH',
        urgencyConfidence: 0.89,
        urgencyReason: 'Food contamination affecting health of multiple resident students.',
        suggestedDepartment: 'HOSTEL_ADMIN',
        departmentConfidence: 0.92,
        alternativeDepartment: 'STUDENT_WELFARE',
        riskFlags: ['POTENTIAL_SAFETY_HAZARD', 'AFFECTING_MULTIPLE_STUDENTS'],
        entities: { location: 'Hostel Dining Hall 2', incidentDate: 'Today morning' },
        detectedLanguage: 'Hinglish',
        normalizedEnglishText: 'Today morning in mess yogurt was completely sour and bread had mold. Multiple students are experiencing mild stomach ache. Please inspect mess hygiene immediately.',
        missingInformation: [],
        requiresHumanReview: true,
        recommendedAction: 'Immediate hygiene audit of kitchen vendor and medical clinic standby.',
        processingTimeMs: 470,
        createdAt: '2026-08-14T02:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'HIGH',
        ruleUrgency: 'MEDIUM',
        finalUrgency: 'HIGH',
        ruleTriggered: true,
        triggeredRules: ['Operational Issue Rule: Detected hygiene keyword [food poisoning]'],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: true,
        routingScore: {
          primaryDept: 'dept-hostel',
          score: 93,
          explanation: 'Hostel Administration handles mess contracts and food quality inspection.',
        },
      },
      isEscalated: false,
      createdAt: '2026-08-14T01:50:00.000Z',
      updatedAt: '2026-08-14T02:05:00.000Z',
    },
    {
      id: 'cmp-1007',
      trackingNumber: 'CMP-2026-1007',
      studentId: 'usr-student-2',
      studentName: 'Rohan Deshmukh',
      studentEmail: 'rohan.d@student.edu',
      studentProgram: 'B.Com Accounting (Final Year)',
      title: 'Hall ticket missing course code ACC-402 for tomorrow morning exam',
      description:
        'My admit card downloaded from student ERP does not show Corporate Taxation (ACC-402). The exam is scheduled for tomorrow at 9:00 AM. I have paid all fees and have 85% attendance.',
      campusLocation: 'Commerce Block',
      isOngoing: true,
      category: 'EXAMS',
      subcategory: 'HALL_TICKET',
      urgency: 'HIGH',
      assignedDepartmentId: 'dept-exam',
      assignedDepartmentName: 'Examination Cell',
      status: 'IN_PROGRESS',
      humanVerified: true,
      humanOverrideApplied: false,
      aiAnalysis: {
        id: 'ai-seed-7',
        complaintId: 'cmp-1007',
        model: 'gemini-3.7-flash',
        summary: 'Missing exam course code ACC-402 on hall ticket with exam scheduled for tomorrow morning.',
        category: 'EXAMS',
        subcategory: 'HALL_TICKET',
        urgency: 'HIGH',
        urgencyConfidence: 0.95,
        urgencyReason: 'Imminent exam deadline tomorrow morning with severe risk of student being barred.',
        suggestedDepartment: 'EXAMINATION_CELL',
        departmentConfidence: 0.97,
        alternativeDepartment: 'ACADEMIC_AFFAIRS',
        riskFlags: ['ACADEMIC_CONSEQUENCE', 'IMMINENT_DEADLINE'],
        entities: { deadline: 'Tomorrow 9:00 AM', equipmentOrItem: 'Course Code ACC-402' },
        detectedLanguage: 'English',
        missingInformation: [],
        requiresHumanReview: true,
        recommendedAction: 'Emergency manual hall ticket endorsement and ERP course registration sync.',
        processingTimeMs: 390,
        createdAt: '2026-08-13T16:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'HIGH',
        ruleUrgency: 'MEDIUM',
        finalUrgency: 'HIGH',
        ruleTriggered: true,
        triggeredRules: ['Operational Issue Rule: Detected deadline keyword [exam hall ticket]'],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: true,
        routingScore: {
          primaryDept: 'dept-exam',
          score: 97,
          explanation: 'Examination Cell handles hall tickets and exam admissions.',
        },
      },
      reviewedById: 'usr-admin-1',
      reviewedByName: 'Dr. Evelyn Vance',
      reviewedAt: '2026-08-13T16:15:00.000Z',
      isEscalated: false,
      createdAt: '2026-08-13T15:50:00.000Z',
      updatedAt: '2026-08-13T16:20:00.000Z',
    },
    {
      id: 'cmp-1008',
      trackingNumber: 'CMP-2026-1008',
      studentId: 'usr-student-3',
      studentName: 'Sarah Jenkins',
      studentEmail: 'sarah.j@student.edu',
      studentProgram: 'B.Sc Biotechnology (2nd Year)',
      title: 'Need guidance regarding interdisciplinary minor elective credit transfer',
      description:
        'I am interested in taking an additional minor in Data Science alongside Biotechnology. Need clarification on whether 6 credits from online NPTEL courses can be counted toward open electives.',
      campusLocation: 'Science Block',
      isOngoing: false,
      category: 'ACADEMICS',
      subcategory: 'COURSE_REGISTRATION',
      urgency: 'LOW',
      assignedDepartmentId: 'dept-academic',
      assignedDepartmentName: 'Academic Affairs',
      status: 'ASSIGNED',
      humanVerified: true,
      humanOverrideApplied: false,
      aiAnalysis: {
        id: 'ai-seed-8',
        complaintId: 'cmp-1008',
        model: 'gemini-3.7-flash',
        summary: 'Student seeking academic guidance regarding elective credit transfer rules.',
        category: 'ACADEMICS',
        subcategory: 'COURSE_REGISTRATION',
        urgency: 'LOW',
        urgencyConfidence: 0.94,
        urgencyReason: 'Routine academic inquiry regarding curriculum guidelines without time pressure.',
        suggestedDepartment: 'ACADEMIC_AFFAIRS',
        departmentConfidence: 0.95,
        riskFlags: [],
        entities: { equipmentOrItem: 'NPTEL 6 credits' },
        detectedLanguage: 'English',
        missingInformation: [],
        requiresHumanReview: false,
        recommendedAction: 'Provide standard credit transfer policy handbook link.',
        processingTimeMs: 360,
        createdAt: '2026-08-13T13:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'LOW',
        ruleUrgency: 'LOW',
        finalUrgency: 'LOW',
        ruleTriggered: false,
        triggeredRules: [],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: false,
        routingScore: {
          primaryDept: 'dept-academic',
          score: 95,
          explanation: 'Academic Affairs handles credit transfer policy.',
        },
      },
      isEscalated: false,
      createdAt: '2026-08-13T12:45:00.000Z',
      updatedAt: '2026-08-13T13:10:00.000Z',
    },
    {
      id: 'cmp-1009',
      trackingNumber: 'CMP-2026-1009',
      studentId: 'usr-student-4',
      studentName: 'Vikram Aditya',
      studentEmail: 'vikram.a@student.edu',
      studentProgram: 'MBA Finance (1st Year)',
      title: 'University Shuttle Route 4 repeatedly skipping Main Gate stop at 8:30 AM',
      description:
        'For the past week, the 8:30 AM morning shuttle bus (Route 4) has been arriving 25 minutes late and skipping the Main Gate bus shelter, forcing day scholars to walk in the rain.',
      campusLocation: 'Campus Main Gate',
      isOngoing: true,
      category: 'TRANSPORT',
      subcategory: 'BUS_ROUTES',
      urgency: 'LOW',
      assignedDepartmentId: 'dept-transport',
      assignedDepartmentName: 'Transport & Logistics',
      status: 'ASSIGNED',
      humanVerified: true,
      humanOverrideApplied: false,
      aiAnalysis: {
        id: 'ai-seed-9',
        complaintId: 'cmp-1009',
        model: 'gemini-3.7-flash',
        summary: 'Campus shuttle Route 4 consistently arriving late and bypassing Main Gate stop.',
        category: 'TRANSPORT',
        subcategory: 'BUS_ROUTES',
        urgency: 'LOW',
        urgencyConfidence: 0.92,
        urgencyReason: 'Routine transport schedule irregularity causing commuter inconvenience.',
        suggestedDepartment: 'TRANSPORT',
        departmentConfidence: 0.98,
        riskFlags: [],
        entities: { location: 'Main Gate Bus Shelter', incidentDate: 'Past 1 week 8:30 AM' },
        detectedLanguage: 'English',
        missingInformation: [],
        requiresHumanReview: false,
        recommendedAction: 'Issue schedule adherence reminder to Route 4 driver and monitor GPS logs.',
        processingTimeMs: 330,
        createdAt: '2026-08-12T10:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'LOW',
        ruleUrgency: 'LOW',
        finalUrgency: 'LOW',
        ruleTriggered: false,
        triggeredRules: [],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: false,
        routingScore: {
          primaryDept: 'dept-transport',
          score: 98,
          explanation: 'Transport category matches Transport department.',
        },
      },
      isEscalated: false,
      createdAt: '2026-08-12T09:45:00.000Z',
      updatedAt: '2026-08-12T10:15:00.000Z',
    },
    {
      id: 'cmp-1010',
      trackingNumber: 'CMP-2026-1010',
      studentId: 'usr-student-5',
      studentName: 'Pooja Nair',
      studentEmail: 'pooja.n@student.edu',
      studentProgram: 'B.A. Economics (1st Year)',
      title: 'Lab 3 Windows workstations blue-screening during statistical econometrics lab',
      description:
        'During today 2:00 PM session in Computer Lab 3, eight workstations suffered repeated BSOD crashes whenever students launched RStudio for econometric regressions.',
      campusLocation: 'Science & Computing Block - Lab 3',
      isOngoing: true,
      category: 'IT',
      subcategory: 'LAB_EQUIPMENT',
      urgency: 'MEDIUM',
      assignedDepartmentId: 'dept-it',
      assignedDepartmentName: 'IT Support & Systems',
      status: 'IN_PROGRESS',
      humanVerified: true,
      humanOverrideApplied: false,
      aiAnalysis: {
        id: 'ai-seed-10',
        complaintId: 'cmp-1010',
        model: 'gemini-3.7-flash',
        summary: 'Multiple lab workstations crashing with BSOD during RStudio econometrics practicals.',
        category: 'IT',
        subcategory: 'LAB_EQUIPMENT',
        urgency: 'MEDIUM',
        urgencyConfidence: 0.93,
        urgencyReason: 'Systemic lab equipment software crash disrupting scheduled academic laboratory sessions.',
        suggestedDepartment: 'IT_SUPPORT',
        departmentConfidence: 0.96,
        riskFlags: ['ACADEMIC_CONSEQUENCE', 'AFFECTING_MULTIPLE_STUDENTS'],
        entities: { location: 'Computer Lab 3', equipmentOrItem: '8 Windows Workstations' },
        detectedLanguage: 'English',
        missingInformation: [],
        requiresHumanReview: false,
        recommendedAction: 'Push updated graphics and RStudio runtime patch across Lab 3 domain machines.',
        processingTimeMs: 370,
        createdAt: '2026-08-13T15:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'MEDIUM',
        ruleUrgency: 'MEDIUM',
        finalUrgency: 'MEDIUM',
        ruleTriggered: true,
        triggeredRules: ['Operational Issue Rule: Detected system crash keyword [lab pc]'],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: false,
        routingScore: {
          primaryDept: 'dept-it',
          score: 96,
          explanation: 'IT Support handles institutional computer labs.',
        },
      },
      isEscalated: false,
      createdAt: '2026-08-13T14:40:00.000Z',
      updatedAt: '2026-08-13T15:30:00.000Z',
    },
    {
      id: 'cmp-1011',
      trackingNumber: 'CMP-2026-1011',
      studentId: 'usr-student-1',
      studentName: 'Aarav Mehta',
      studentEmail: 'aarav.mehta@student.edu',
      studentProgram: 'B.Tech Computer Science (3rd Year)',
      title: 'Ambiguous noise disturbance near campus boundary wall at night',
      description:
        'There are loud repetitive thuds and vehicle noises coming from beyond the perimeter fence between 1:00 AM and 3:00 AM. Hard to tell if construction or trespassers.',
      campusLocation: 'North Perimeter Wall',
      isOngoing: true,
      category: 'SAFETY',
      subcategory: 'CAMPUS_SECURITY',
      urgency: 'MEDIUM',
      assignedDepartmentId: 'dept-security',
      assignedDepartmentName: 'Campus Security & Safety',
      status: 'REVIEW_REQUIRED',
      humanVerified: false,
      humanOverrideApplied: false,
      aiAnalysis: {
        id: 'ai-seed-11',
        complaintId: 'cmp-1011',
        model: 'gemini-3.7-flash',
        summary: 'Unidentified night-time noise and activity near north perimeter fence.',
        category: 'SAFETY',
        subcategory: 'CAMPUS_SECURITY',
        urgency: 'MEDIUM',
        urgencyConfidence: 0.68, // Low confidence case demonstrating human review queue!
        urgencyReason: 'Ambiguous situation near perimeter fence with potential security implications.',
        suggestedDepartment: 'SECURITY',
        departmentConfidence: 0.72,
        alternativeDepartment: 'GENERAL_ADMIN',
        riskFlags: ['POTENTIAL_SAFETY_HAZARD'],
        entities: { location: 'North Perimeter Wall' },
        detectedLanguage: 'English',
        missingInformation: ['Specific nature of activity', 'Visual identification'],
        requiresHumanReview: true,
        recommendedAction: 'Security patrol checkpoint inspection during designated hours.',
        processingTimeMs: 440,
        createdAt: '2026-08-14T03:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'MEDIUM',
        ruleUrgency: 'LOW',
        finalUrgency: 'MEDIUM',
        ruleTriggered: false,
        triggeredRules: [],
        confidenceStatus: 'NEEDS_REVIEW',
        requiresHumanReview: true,
        routingScore: {
          primaryDept: 'dept-security',
          score: 72,
          explanation: 'Low confidence AI match (72%) flagged for administrative confirmation.',
        },
      },
      isEscalated: false,
      createdAt: '2026-08-14T02:45:00.000Z',
      updatedAt: '2026-08-14T03:05:00.000Z',
    },
    {
      id: 'cmp-1012',
      trackingNumber: 'CMP-2026-1012',
      studentId: 'usr-student-2',
      studentName: 'Rohan Deshmukh',
      studentEmail: 'rohan.d@student.edu',
      studentProgram: 'B.Com Accounting (Final Year)',
      title: 'Elevator in Management Building stuck twice with students inside (Safety Hazard)',
      description:
        'Elevator #2 in the Management block stopped between 3rd and 4th floors yesterday with 6 students trapped in pitch dark for 35 minutes before emergency release. This happened once last week too.',
      campusLocation: 'Management Block - Lift #2',
      isOngoing: true,
      category: 'FACILITIES',
      subcategory: 'ELEVATOR_MAINTENANCE',
      urgency: 'HIGH',
      assignedDepartmentId: 'dept-facilities',
      assignedDepartmentName: 'Facilities & Maintenance',
      status: 'ESCALATED', // Escalated SLA breach test case!
      humanVerified: true,
      humanOverrideApplied: false,
      aiAnalysis: {
        id: 'ai-seed-12',
        complaintId: 'cmp-1012',
        model: 'gemini-3.7-flash',
        summary: 'Elevator #2 trapped students between floors for 35 minutes in recurring failure.',
        category: 'FACILITIES',
        subcategory: 'ELEVATOR_MAINTENANCE',
        urgency: 'HIGH',
        urgencyConfidence: 0.97,
        urgencyReason: 'Recurring elevator entrapment poses severe claustrophobia, panic, and physical safety threat.',
        suggestedDepartment: 'FACILITIES',
        departmentConfidence: 0.95,
        alternativeDepartment: 'SECURITY',
        riskFlags: ['POTENTIAL_SAFETY_HAZARD', 'AFFECTING_MULTIPLE_STUDENTS'],
        entities: { location: 'Management Block Lift #2', equipmentOrItem: 'Elevator #2' },
        detectedLanguage: 'English',
        missingInformation: [],
        requiresHumanReview: true,
        recommendedAction: 'Immediate shutdown of Elevator #2 pending certified OEM inspection.',
        processingTimeMs: 400,
        createdAt: '2026-08-11T11:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'HIGH',
        ruleUrgency: 'HIGH',
        finalUrgency: 'HIGH',
        ruleTriggered: true,
        triggeredRules: ['Deterministic Safety Override: Detected hazard keyword [elevator trapped]'],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: true,
        routingScore: {
          primaryDept: 'dept-facilities',
          score: 95,
          explanation: 'Facilities department manages heavy mechanical systems and elevators.',
        },
      },
      isEscalated: true,
      escalationDeadline: '2026-08-11T19:00:00.000Z',
      createdAt: '2026-08-11T10:45:00.000Z',
      updatedAt: '2026-08-12T19:05:00.000Z',
    },
    {
      id: 'cmp-1013',
      trackingNumber: 'CMP-2026-1013',
      studentId: 'usr-student-3',
      studentName: 'Sarah Jenkins',
      studentEmail: 'sarah.j@student.edu',
      studentProgram: 'B.Sc Biotechnology (2nd Year)',
      title: 'Merit-cum-means scholarship disbursement delayed for semester 4',
      description:
        'State government merit scholarship was sanctioned 6 weeks ago but accounts department has not credited the balance to my fee ledger. Late fee penalty is showing on my portal.',
      campusLocation: 'Administrative Block',
      isOngoing: true,
      category: 'FINANCE',
      subcategory: 'SCHOLARSHIP',
      urgency: 'MEDIUM',
      assignedDepartmentId: 'dept-finance',
      assignedDepartmentName: 'Finance & Accounts',
      status: 'ASSIGNED',
      humanVerified: true,
      humanOverrideApplied: false,
      aiAnalysis: {
        id: 'ai-seed-13',
        complaintId: 'cmp-1013',
        model: 'gemini-3.7-flash',
        summary: 'Scholarship disbursement delayed 6 weeks with erroneous late fee penalty applied.',
        category: 'FINANCE',
        subcategory: 'SCHOLARSHIP',
        urgency: 'MEDIUM',
        urgencyConfidence: 0.94,
        urgencyReason: 'Financial delay causing unjust academic late penalty ledger charge.',
        suggestedDepartment: 'FINANCE',
        departmentConfidence: 0.97,
        riskFlags: ['FINANCIAL_DISCREPANCY'],
        entities: { equipmentOrItem: 'Semester 4 State Merit Scholarship' },
        detectedLanguage: 'English',
        missingInformation: [],
        requiresHumanReview: false,
        recommendedAction: 'Verify state treasury credit and waive late fee penalty.',
        processingTimeMs: 380,
        createdAt: '2026-08-12T16:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'MEDIUM',
        ruleUrgency: 'MEDIUM',
        finalUrgency: 'MEDIUM',
        ruleTriggered: true,
        triggeredRules: ['Operational Issue Rule: Detected financial keyword [scholarship delay]'],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: false,
        routingScore: {
          primaryDept: 'dept-finance',
          score: 97,
          explanation: 'Finance department administers scholarship credit ledgers.',
        },
      },
      isEscalated: false,
      createdAt: '2026-08-12T15:45:00.000Z',
      updatedAt: '2026-08-12T16:20:00.000Z',
    },
    {
      id: 'cmp-1014',
      trackingNumber: 'CMP-2026-1014',
      studentId: 'usr-student-4',
      studentName: 'Vikram Aditya',
      studentEmail: 'vikram.a@student.edu',
      studentProgram: 'MBA Finance (1st Year)',
      title: 'Discrepancy in recorded attendance percentage for Corporate Strategy course',
      description:
        'My recorded attendance for MGT-501 is showing 68% whereas according to my physical signature in class register I have attended 22 out of 25 lectures (88%). Below 75% will disallow exam appearance.',
      campusLocation: 'Management Block',
      isOngoing: true,
      category: 'ACADEMICS',
      subcategory: 'ATTENDANCE',
      urgency: 'MEDIUM',
      assignedDepartmentId: 'dept-academic',
      assignedDepartmentName: 'Academic Affairs',
      status: 'IN_PROGRESS',
      humanVerified: true,
      humanOverrideApplied: false,
      aiAnalysis: {
        id: 'ai-seed-14',
        complaintId: 'cmp-1014',
        model: 'gemini-3.7-flash',
        summary: 'Discrepancy between physical attendance register (88%) and ERP record (68%) threatening exam eligibility.',
        category: 'ACADEMICS',
        subcategory: 'ATTENDANCE',
        urgency: 'MEDIUM',
        urgencyConfidence: 0.92,
        urgencyReason: 'Attendance calculation error could lead to debarment from final semester exams.',
        suggestedDepartment: 'ACADEMIC_AFFAIRS',
        departmentConfidence: 0.94,
        alternativeDepartment: 'EXAMINATION_CELL',
        riskFlags: ['ACADEMIC_CONSEQUENCE'],
        entities: { equipmentOrItem: 'Course MGT-501' },
        detectedLanguage: 'English',
        missingInformation: [],
        requiresHumanReview: false,
        recommendedAction: 'Cross-check physical faculty roll with ERP data entry.',
        processingTimeMs: 390,
        createdAt: '2026-08-13T09:30:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'MEDIUM',
        ruleUrgency: 'MEDIUM',
        finalUrgency: 'MEDIUM',
        ruleTriggered: true,
        triggeredRules: ['Operational Issue Rule: Detected academic keyword [attendance shortage]'],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: false,
        routingScore: {
          primaryDept: 'dept-academic',
          score: 94,
          explanation: 'Academic Affairs coordinates faculty attendance audits.',
        },
      },
      isEscalated: false,
      createdAt: '2026-08-13T09:15:00.000Z',
      updatedAt: '2026-08-13T10:00:00.000Z',
    },
    {
      id: 'cmp-1015',
      trackingNumber: 'CMP-2026-1015',
      studentId: 'usr-student-5',
      studentName: 'Pooja Nair',
      studentEmail: 'pooja.n@student.edu',
      studentProgram: 'B.A. Economics (1st Year)',
      title: 'Geyser non-functional in Hostel Block D ground floor washroom',
      description:
        'The electric water heater / geyser in ground floor washroom of Block D has stopped heating since Monday. Water is cold.',
      campusLocation: 'Hostel Block D Washroom',
      isOngoing: true,
      category: 'FACILITIES',
      subcategory: 'PLUMBING_ELECTRICAL',
      urgency: 'LOW',
      assignedDepartmentId: 'dept-facilities',
      assignedDepartmentName: 'Facilities & Maintenance',
      status: 'RESOLVED',
      humanVerified: true,
      humanOverrideApplied: false,
      aiAnalysis: {
        id: 'ai-seed-15',
        complaintId: 'cmp-1015',
        model: 'gemini-3.7-flash',
        summary: 'Geyser heating element failure in Hostel Block D ground floor washroom.',
        category: 'FACILITIES',
        subcategory: 'PLUMBING_ELECTRICAL',
        urgency: 'LOW',
        urgencyConfidence: 0.95,
        urgencyReason: 'Routine appliance maintenance without safety hazard.',
        suggestedDepartment: 'FACILITIES',
        departmentConfidence: 0.92,
        alternativeDepartment: 'HOSTEL_ADMIN',
        riskFlags: [],
        entities: { location: 'Hostel Block D Ground Floor' },
        detectedLanguage: 'English',
        missingInformation: [],
        requiresHumanReview: false,
        recommendedAction: 'Replace geyser heating coil.',
        processingTimeMs: 320,
        createdAt: '2026-08-11T08:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'LOW',
        ruleUrgency: 'LOW',
        finalUrgency: 'LOW',
        ruleTriggered: false,
        triggeredRules: [],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: false,
        routingScore: {
          primaryDept: 'dept-facilities',
          score: 92,
          explanation: 'Facilities maintenance handles electrical appliances.',
        },
      },
      studentFeedback: {
        satisfactionScore: 5,
        comment: 'Technician repaired it the same afternoon. Very satisfied.',
        markedAsResolved: true,
        submittedAt: '2026-08-11T17:00:00.000Z',
      },
      isEscalated: false,
      createdAt: '2026-08-11T07:45:00.000Z',
      updatedAt: '2026-08-11T16:30:00.000Z',
      resolvedAt: '2026-08-11T16:30:00.000Z',
    },
    {
      id: 'cmp-1016',
      trackingNumber: 'CMP-2026-1016',
      studentId: 'usr-student-1',
      studentName: 'Aarav Mehta',
      studentEmail: 'aarav.mehta@student.edu',
      studentProgram: 'B.Tech Computer Science (3rd Year)',
      title: 'Hindi Submission: Kamre ki khidki ka kanch toota hua hai (Broken window glass in hostel)',
      description:
        'Kripya dhyan dein, mere hostel room number 308 ki khidki ka kanch kal sham tej hawa se toot gaya hai. Barish ka pani andar aa raha hai.',
      campusLocation: 'Hostel Block B Room 308',
      isOngoing: true,
      category: 'HOSTEL',
      subcategory: 'ROOM_MAINTENANCE',
      urgency: 'MEDIUM',
      assignedDepartmentId: 'dept-facilities',
      assignedDepartmentName: 'Facilities & Maintenance',
      status: 'ASSIGNED',
      humanVerified: true,
      humanOverrideApplied: false,
      aiAnalysis: {
        id: 'ai-seed-16',
        complaintId: 'cmp-1016',
        model: 'gemini-3.7-flash',
        summary: 'Window glass broken in Hostel Room 308 allowing rainwater into room.',
        category: 'HOSTEL',
        subcategory: 'ROOM_MAINTENANCE',
        urgency: 'MEDIUM',
        urgencyConfidence: 0.93,
        urgencyReason: 'Broken glass and rain ingress causing living disruption and potential cut hazard.',
        suggestedDepartment: 'FACILITIES',
        departmentConfidence: 0.91,
        alternativeDepartment: 'HOSTEL_ADMIN',
        riskFlags: ['INFRASTRUCTURE_FAILURE'],
        entities: { location: 'Hostel Block B Room 308' },
        detectedLanguage: 'Hindi / Hinglish',
        normalizedEnglishText: 'Please note, the window glass in my hostel room number 308 was shattered yesterday evening due to strong wind. Rainwater is entering inside.',
        missingInformation: [],
        requiresHumanReview: false,
        recommendedAction: 'Carpentry and glazing replacement.',
        processingTimeMs: 410,
        createdAt: '2026-08-13T18:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'MEDIUM',
        ruleUrgency: 'MEDIUM',
        finalUrgency: 'MEDIUM',
        ruleTriggered: false,
        triggeredRules: [],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: false,
        routingScore: {
          primaryDept: 'dept-facilities',
          score: 91,
          explanation: 'Facilities civil maintenance handles window repairs.',
        },
      },
      isEscalated: false,
      createdAt: '2026-08-13T17:45:00.000Z',
      updatedAt: '2026-08-13T18:15:00.000Z',
    },
    {
      id: 'cmp-1017',
      trackingNumber: 'CMP-2026-1017',
      studentId: 'usr-student-2',
      studentName: 'Rohan Deshmukh',
      studentEmail: 'rohan.d@student.edu',
      studentProgram: 'B.Com Accounting (Final Year)',
      title: 'Digital library proxy server connection timing out off-campus',
      description:
        'The EZproxy remote library login for IEEE and ScienceDirect digital journals keeps timing out when attempting to research from home network.',
      campusLocation: 'Off Campus / Remote',
      isOngoing: true,
      category: 'LIBRARY',
      subcategory: 'DIGITAL_ACCESS',
      urgency: 'LOW',
      assignedDepartmentId: 'dept-library',
      assignedDepartmentName: 'University Library',
      status: 'ASSIGNED',
      humanVerified: true,
      humanOverrideApplied: false,
      aiAnalysis: {
        id: 'ai-seed-17',
        complaintId: 'cmp-1017',
        model: 'gemini-3.7-flash',
        summary: 'Off-campus EZproxy timeout accessing IEEE and ScienceDirect journal repositories.',
        category: 'LIBRARY',
        subcategory: 'DIGITAL_ACCESS',
        urgency: 'LOW',
        urgencyConfidence: 0.9,
        urgencyReason: 'Technical proxy configuration query for off-campus digital journal access.',
        suggestedDepartment: 'LIBRARY',
        departmentConfidence: 0.88,
        alternativeDepartment: 'IT_SUPPORT',
        riskFlags: [],
        entities: { equipmentOrItem: 'EZproxy / IEEE / ScienceDirect' },
        detectedLanguage: 'English',
        missingInformation: [],
        requiresHumanReview: false,
        recommendedAction: 'Verify proxy certificate and send updated off-campus URL handbook.',
        processingTimeMs: 350,
        createdAt: '2026-08-12T11:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'LOW',
        ruleUrgency: 'LOW',
        finalUrgency: 'LOW',
        ruleTriggered: false,
        triggeredRules: [],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: false,
        routingScore: {
          primaryDept: 'dept-library',
          score: 88,
          explanation: 'Library department manages digital journal database licenses.',
        },
      },
      isEscalated: false,
      createdAt: '2026-08-12T10:45:00.000Z',
      updatedAt: '2026-08-12T11:15:00.000Z',
    },
    {
      id: 'cmp-1018',
      trackingNumber: 'CMP-2026-1018',
      studentId: 'usr-student-3',
      studentName: 'Sarah Jenkins',
      studentEmail: 'sarah.j@student.edu',
      studentProgram: 'B.Sc Biotechnology (2nd Year)',
      title: 'Report of verbal harassment and intimidation outside girl student hostel gate',
      description:
        'A group of unidentified individuals was standing near the East Hostel gate making derogatory comments and filming female students entering after 8:00 PM yesterday.',
      campusLocation: 'East Hostel Gate',
      isOngoing: true,
      category: 'SAFETY',
      subcategory: 'HARASSMENT_DISCRIMINATION',
      urgency: 'HIGH',
      assignedDepartmentId: 'dept-security',
      assignedDepartmentName: 'Campus Security & Safety',
      status: 'IN_PROGRESS',
      humanVerified: true,
      humanOverrideApplied: false,
      aiAnalysis: {
        id: 'ai-seed-18',
        complaintId: 'cmp-1018',
        model: 'gemini-3.7-flash',
        summary: 'Report of verbal harassment and non-consensual filming outside East Hostel gate at night.',
        category: 'SAFETY',
        subcategory: 'HARASSMENT_DISCRIMINATION',
        urgency: 'HIGH',
        urgencyConfidence: 0.98,
        urgencyReason: 'Harassment and intimidation of students outside hostel gates poses immediate safety and security violation.',
        suggestedDepartment: 'SECURITY',
        departmentConfidence: 0.98,
        alternativeDepartment: 'STUDENT_WELFARE',
        riskFlags: ['HARASSMENT_DISCRIMINATION', 'POTENTIAL_SAFETY_HAZARD'],
        entities: { location: 'East Hostel Gate', incidentDate: 'Yesterday 8:00 PM' },
        detectedLanguage: 'English',
        missingInformation: [],
        requiresHumanReview: true,
        recommendedAction: 'Deploy stationary guard post, review CCTV footage, and alert campus proctorial board.',
        processingTimeMs: 430,
        createdAt: '2026-08-13T08:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'HIGH',
        ruleUrgency: 'HIGH',
        finalUrgency: 'HIGH',
        ruleTriggered: true,
        triggeredRules: ['Deterministic Safety Override: Detected harassment/intimidation keyword [harassment]'],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: true,
        routingScore: {
          primaryDept: 'dept-security',
          score: 98,
          explanation: 'Security department manages campus gates, surveillance, and physical protection.',
        },
      },
      reviewedById: 'usr-admin-1',
      reviewedByName: 'Dr. Evelyn Vance',
      reviewedAt: '2026-08-13T08:15:00.000Z',
      isEscalated: false,
      createdAt: '2026-08-13T07:45:00.000Z',
      updatedAt: '2026-08-13T08:30:00.000Z',
    },
    {
      id: 'cmp-1019',
      trackingNumber: 'CMP-2026-1019',
      studentId: 'usr-student-4',
      studentName: 'Vikram Aditya',
      studentEmail: 'vikram.a@student.edu',
      studentProgram: 'MBA Finance (1st Year)',
      title: 'Smart classroom projector lamp flickering heavily in Management Room 302',
      description:
        'The overhead HDMI ceiling projector in Room 302 shuts down every 10 minutes with an overheating warning during case study presentations.',
      campusLocation: 'Management Block - Room 302',
      isOngoing: true,
      category: 'IT',
      subcategory: 'LAB_EQUIPMENT',
      urgency: 'LOW',
      assignedDepartmentId: 'dept-it',
      assignedDepartmentName: 'IT Support & Systems',
      status: 'RESOLVED',
      humanVerified: true,
      humanOverrideApplied: false,
      aiAnalysis: {
        id: 'ai-seed-19',
        complaintId: 'cmp-1019',
        model: 'gemini-3.7-flash',
        summary: 'Smart classroom projector overheating and cycling power in Room 302.',
        category: 'IT',
        subcategory: 'LAB_EQUIPMENT',
        urgency: 'LOW',
        urgencyConfidence: 0.94,
        urgencyReason: 'Audio-visual classroom hardware issue causing minor presentation disruption.',
        suggestedDepartment: 'IT_SUPPORT',
        departmentConfidence: 0.96,
        alternativeDepartment: 'FACILITIES',
        riskFlags: [],
        entities: { location: 'Management Block Room 302', equipmentOrItem: 'Ceiling Projector' },
        detectedLanguage: 'English',
        missingInformation: [],
        requiresHumanReview: false,
        recommendedAction: 'Clean projector air filter and replace thermal lamp.',
        processingTimeMs: 330,
        createdAt: '2026-08-11T13:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'LOW',
        ruleUrgency: 'LOW',
        finalUrgency: 'LOW',
        ruleTriggered: false,
        triggeredRules: [],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: false,
        routingScore: {
          primaryDept: 'dept-it',
          score: 96,
          explanation: 'IT Support manages smart classroom audio-visual installations.',
        },
      },
      studentFeedback: {
        satisfactionScore: 5,
        comment: 'Projector lamp replaced before next morning lecture.',
        markedAsResolved: true,
        submittedAt: '2026-08-12T10:00:00.000Z',
      },
      isEscalated: false,
      createdAt: '2026-08-11T12:45:00.000Z',
      updatedAt: '2026-08-12T09:30:00.000Z',
      resolvedAt: '2026-08-12T09:30:00.000Z',
    },
    {
      id: 'cmp-1020',
      trackingNumber: 'CMP-2026-1020',
      studentId: 'usr-student-5',
      studentName: 'Pooja Nair',
      studentEmail: 'pooja.n@student.edu',
      studentProgram: 'B.A. Economics (1st Year)',
      title: 'Disability ramp at South Campus cafeteria obstructed by heavy supply crates',
      description:
        'The wheelchair ramp leading to the ground floor cafeteria has been blocked by kitchen beverage crates and empty wooden pallets for 3 days, making access impossible for wheelchair users.',
      campusLocation: 'South Campus Cafeteria',
      isOngoing: true,
      category: 'STUDENT_WELFARE',
      subcategory: 'DISABILITY_ACCESS',
      urgency: 'HIGH',
      assignedDepartmentId: 'dept-welfare',
      assignedDepartmentName: 'Student Welfare & Counseling',
      status: 'IN_PROGRESS',
      humanVerified: true,
      humanOverrideApplied: true, // Example of human override where AI suggested Facilities but human rerouted to Welfare
      overrideReason: 'Reassigned from Facilities to Student Welfare to enforce institutional disability accessibility policy and issue notice to cafeteria contractor.',
      aiAnalysis: {
        id: 'ai-seed-20',
        complaintId: 'cmp-1020',
        model: 'gemini-3.7-flash',
        summary: 'Wheelchair access ramp to South Campus cafeteria obstructed by crates for 3 days.',
        category: 'FACILITIES',
        subcategory: 'CIVIL_MAINTENANCE',
        urgency: 'HIGH',
        urgencyConfidence: 0.91,
        urgencyReason: 'Obstructed disability access violates institutional accessibility guidelines and prevents essential building entry.',
        suggestedDepartment: 'FACILITIES',
        departmentConfidence: 0.82,
        alternativeDepartment: 'STUDENT_WELFARE',
        riskFlags: ['CRITICAL_ACCESS_BLOCK', 'POTENTIAL_DISCRIMINATION'],
        entities: { location: 'South Campus Cafeteria Wheelchair Ramp' },
        detectedLanguage: 'English',
        missingInformation: [],
        requiresHumanReview: true,
        recommendedAction: 'Immediate clearance of crates and warning notice to cafeteria vendor.',
        processingTimeMs: 410,
        createdAt: '2026-08-13T10:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'HIGH',
        ruleUrgency: 'MEDIUM',
        finalUrgency: 'HIGH',
        ruleTriggered: false,
        triggeredRules: [],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: true,
        routingScore: {
          primaryDept: 'dept-facilities',
          score: 82,
          explanation: 'Facilities manages physical ramp clearances.',
        },
      },
      reviewedById: 'usr-admin-1',
      reviewedByName: 'Dr. Evelyn Vance',
      reviewedAt: '2026-08-13T10:30:00.000Z',
      isEscalated: false,
      createdAt: '2026-08-13T09:45:00.000Z',
      updatedAt: '2026-08-13T10:45:00.000Z',
    },
    {
      id: 'cmp-1021',
      trackingNumber: 'CMP-2026-1021',
      studentId: 'usr-student-1',
      studentName: 'Aarav Mehta',
      studentEmail: 'aarav.mehta@student.edu',
      studentProgram: 'B.Tech Computer Science (3rd Year)',
      title: 'Possible Duplicate: Wi-Fi dead zone in Hostel Block C rooms 301 to 310',
      description:
        'Wi-Fi signal dropped completely in Hostel C 3rd floor wing since Monday. Cannot load online coding assignments.',
      campusLocation: 'South Campus - Hostel Block C',
      isOngoing: true,
      category: 'IT',
      subcategory: 'WIFI_NETWORK',
      urgency: 'MEDIUM',
      assignedDepartmentId: 'dept-it',
      assignedDepartmentName: 'IT Support & Systems',
      status: 'ASSIGNED',
      humanVerified: true,
      humanOverrideApplied: false,
      possibleDuplicateOf: ['CMP-2026-1003'], // Example of duplicate linking!
      aiAnalysis: {
        id: 'ai-seed-21',
        complaintId: 'cmp-1021',
        model: 'gemini-3.7-flash',
        summary: 'Wi-Fi outage in Hostel Block C 3rd floor wing affecting rooms 301-310.',
        category: 'IT',
        subcategory: 'WIFI_NETWORK',
        urgency: 'MEDIUM',
        urgencyConfidence: 0.92,
        urgencyReason: 'Corroborating network outage report for Hostel Block C.',
        suggestedDepartment: 'IT_SUPPORT',
        departmentConfidence: 0.96,
        riskFlags: ['ACADEMIC_CONSEQUENCE'],
        entities: { location: 'Hostel Block C 3rd Floor' },
        detectedLanguage: 'English',
        missingInformation: [],
        requiresHumanReview: false,
        recommendedAction: 'Link with ticket CMP-2026-1003 for unified AP maintenance.',
        processingTimeMs: 360,
        createdAt: '2026-08-14T01:00:00.000Z',
        status: 'SUCCESS',
      },
      ruleEvaluation: {
        aiUrgency: 'MEDIUM',
        ruleUrgency: 'MEDIUM',
        finalUrgency: 'MEDIUM',
        ruleTriggered: true,
        triggeredRules: ['Operational Issue Rule: Detected network connectivity keyword [wifi]'],
        confidenceStatus: 'AUTO_ACCEPT',
        requiresHumanReview: false,
        routingScore: {
          primaryDept: 'dept-it',
          score: 96,
          explanation: 'IT Support handles campus access points.',
        },
      },
      isEscalated: false,
      createdAt: '2026-08-14T00:50:00.000Z',
      updatedAt: '2026-08-14T01:15:00.000Z',
    },
  ];

  const auditLogs: AuditLog[] = [
    {
      id: 'log-1',
      complaintId: 'cmp-1001',
      trackingNumber: 'CMP-2026-1001',
      actorId: 'usr-student-1',
      actorName: 'Aarav Mehta',
      actorRole: 'STUDENT',
      action: 'SUBMITTED',
      newValue: 'Exposed live electrical wiring in Hostel B',
      createdAt: '2026-08-12T14:05:00.000Z',
    },
    {
      id: 'log-2',
      complaintId: 'cmp-1001',
      trackingNumber: 'CMP-2026-1001',
      actorId: 'system-ai',
      actorName: 'Gemini AI Engine',
      actorRole: 'ADMIN',
      action: 'AI_ANALYSED',
      newValue: 'Urgency: HIGH, Dept: FACILITIES, Conf: 96%',
      createdAt: '2026-08-12T14:10:00.000Z',
    },
    {
      id: 'log-3',
      complaintId: 'cmp-1001',
      trackingNumber: 'CMP-2026-1001',
      actorId: 'usr-staff-facilities',
      actorName: 'Rajesh Kumar',
      actorRole: 'STAFF',
      action: 'ROUTED',
      newValue: 'Facilities & Maintenance (Approved)',
      createdAt: '2026-08-12T14:25:00.000Z',
    },
    {
      id: 'log-4',
      complaintId: 'cmp-1004',
      trackingNumber: 'CMP-2026-1004',
      actorId: 'usr-staff-hostel',
      actorName: 'Anita Sharma',
      actorRole: 'STAFF',
      action: 'DEPARTMENT_OVERRIDDEN',
      oldValue: 'FACILITIES',
      newValue: 'HOSTEL_ADMIN',
      reason: 'Reassigned from Facilities to Hostel Admin for immediate student room relocation while repairs occur.',
      createdAt: '2026-08-12T09:30:00.000Z',
    },
    {
      id: 'log-5',
      complaintId: 'cmp-1020',
      trackingNumber: 'CMP-2026-1020',
      actorId: 'usr-admin-1',
      actorName: 'Dr. Evelyn Vance',
      actorRole: 'ADMIN',
      action: 'DEPARTMENT_OVERRIDDEN',
      oldValue: 'FACILITIES',
      newValue: 'STUDENT_WELFARE',
      reason: 'Reassigned from Facilities to Student Welfare to enforce institutional disability accessibility policy and issue notice to cafeteria contractor.',
      createdAt: '2026-08-13T10:30:00.000Z',
    },
  ];

  const feedback: AIFeedbackRecord[] = [
    {
      id: 'fb-1',
      complaintId: 'cmp-1004',
      trackingNumber: 'CMP-2026-1004',
      aiAnalysisId: 'ai-seed-4',
      feedbackType: 'WRONG_DEPARTMENT',
      originalAISuggestion: {
        category: 'FACILITIES',
        urgency: 'MEDIUM',
        department: 'FACILITIES',
        confidence: 0.86,
      },
      humanCorrection: {
        department: 'HOSTEL_ADMIN',
      },
      explanation: 'While civil repairs are needed, the immediate administrative priority was student room reallocation which must be handled by Hostel Administration.',
      reviewerId: 'usr-staff-hostel',
      reviewerName: 'Anita Sharma',
      reviewerRole: 'STAFF',
      createdAt: '2026-08-12T09:32:00.000Z',
    },
    {
      id: 'fb-2',
      complaintId: 'cmp-1020',
      trackingNumber: 'CMP-2026-1020',
      aiAnalysisId: 'ai-seed-20',
      feedbackType: 'MISSING_CONTEXT',
      originalAISuggestion: {
        category: 'FACILITIES',
        urgency: 'HIGH',
        department: 'FACILITIES',
        confidence: 0.82,
      },
      humanCorrection: {
        department: 'STUDENT_WELFARE',
        category: 'STUDENT_WELFARE',
      },
      explanation: 'Obstruction of disability infrastructure is a statutory compliance and student advocacy concern that belongs to Student Welfare.',
      reviewerId: 'usr-admin-1',
      reviewerName: 'Dr. Evelyn Vance',
      reviewerRole: 'ADMIN',
      createdAt: '2026-08-13T10:35:00.000Z',
    },
  ];

  const notes: InternalNote[] = [
    {
      id: 'note-1',
      complaintId: 'cmp-1001',
      authorId: 'usr-staff-facilities',
      authorName: 'Rajesh Kumar',
      authorRole: 'STAFF',
      text: 'Electrician team dispatched at 14:30 with hazard cones. Switchboard isolated on main MCB.',
      createdAt: '2026-08-12T14:35:00.000Z',
    },
    {
      id: 'note-2',
      complaintId: 'cmp-1002',
      authorId: 'usr-staff-finance',
      authorName: 'Priya Patel',
      authorRole: 'STAFF',
      text: 'Verified duplicate charge on HDFC merchant portal. Refund batch ID REF-8821 triggered.',
      createdAt: '2026-08-11T10:30:00.000Z',
    },
  ];

  return { complaints, auditLogs, feedback, notes };
}

class DatabaseManager {
  private db: AppDatabase;

  constructor() {
    this.db = this.loadDatabase();
  }

  private loadDatabase(): AppDatabase {
    try {
      if (!fs.existsSync(DATA_DIR)) {
        fs.mkdirSync(DATA_DIR, { recursive: true });
      }
      if (fs.existsSync(DB_FILE)) {
        const raw = fs.readFileSync(DB_FILE, 'utf-8');
        return JSON.parse(raw);
      }
    } catch (err) {
      console.warn('Could not read persistent database. Initializing default seed data.', err);
    }

    const { complaints, auditLogs, feedback, notes } = generateSeedComplaints();
    const initialDb: AppDatabase = {
      users: INITIAL_USERS,
      departments: INITIAL_DEPARTMENTS,
      complaints,
      auditLogs,
      feedback,
      internalNotes: notes,
      statusUpdates: [],
      clarifications: [],
      settings: INITIAL_SETTINGS,
    };
    this.saveDatabase(initialDb);
    return initialDb;
  }

  public saveDatabase(data?: AppDatabase): void {
    try {
      if (data) this.db = data;
      if (!fs.existsSync(DATA_DIR)) {
        fs.mkdirSync(DATA_DIR, { recursive: true });
      }
      fs.writeFileSync(DB_FILE, JSON.stringify(this.db, null, 2), 'utf-8');
    } catch (err) {
      console.error('Failed to persist database file:', err);
    }
  }

  public resetToSeed(): AppDatabase {
    const { complaints, auditLogs, feedback, notes } = generateSeedComplaints();
    this.db = {
      users: INITIAL_USERS,
      departments: INITIAL_DEPARTMENTS,
      complaints,
      auditLogs,
      feedback,
      internalNotes: notes,
      statusUpdates: [],
      clarifications: [],
      settings: INITIAL_SETTINGS,
    };
    this.saveDatabase();
    return this.db;
  }

  public getSnapshot(): AppDatabase {
    return this.db;
  }

  // Users
  public getUsers(): User[] {
    return this.db.users;
  }
  public getUserById(id: string): User | undefined {
    return this.db.users.find((u) => u.id === id);
  }

  // Departments
  public getDepartments(): Department[] {
    return this.db.departments;
  }
  public getDepartmentById(id: string): Department | undefined {
    return this.db.departments.find((d) => d.id === id || d.code === id);
  }
  public createDepartment(dept: Department): Department {
    this.db.departments.push(dept);
    this.saveDatabase();
    return dept;
  }
  public updateDepartment(id: string, updates: Partial<Department>): Department | null {
    const idx = this.db.departments.findIndex((d) => d.id === id || d.code === id);
    if (idx === -1) return null;
    this.db.departments[idx] = { ...this.db.departments[idx], ...updates };
    this.saveDatabase();
    return this.db.departments[idx];
  }

  // Complaints
  public getComplaints(): Complaint[] {
    return this.db.complaints;
  }
  public getComplaintById(id: string): Complaint | undefined {
    return this.db.complaints.find((c) => c.id === id || c.trackingNumber === id);
  }
  public createComplaint(complaint: Complaint): Complaint {
    this.db.complaints.unshift(complaint);
    this.saveDatabase();
    return complaint;
  }
  public updateComplaint(id: string, updates: Partial<Complaint>): Complaint | null {
    const idx = this.db.complaints.findIndex((c) => c.id === id || c.trackingNumber === id);
    if (idx === -1) return null;
    this.db.complaints[idx] = { ...this.db.complaints[idx], ...updates, updatedAt: new Date().toISOString() };
    this.saveDatabase();
    return this.db.complaints[idx];
  }

  // Audit Logs
  public getAuditLogs(complaintId?: string): AuditLog[] {
    if (complaintId) {
      return this.db.auditLogs.filter((l) => l.complaintId === complaintId || l.trackingNumber === complaintId);
    }
    return this.db.auditLogs;
  }
  public addAuditLog(log: Omit<AuditLog, 'id' | 'createdAt'>): AuditLog {
    const newLog: AuditLog = {
      ...log,
      id: `log-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
      createdAt: new Date().toISOString(),
    };
    this.db.auditLogs.unshift(newLog);
    this.saveDatabase();
    return newLog;
  }

  // Feedback
  public getFeedback(): AIFeedbackRecord[] {
    return this.db.feedback;
  }
  public addFeedback(fb: Omit<AIFeedbackRecord, 'id' | 'createdAt'>): AIFeedbackRecord {
    const newFb: AIFeedbackRecord = {
      ...fb,
      id: `fb-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
      createdAt: new Date().toISOString(),
    };
    this.db.feedback.unshift(newFb);
    this.saveDatabase();
    return newFb;
  }

  // Internal Notes
  public getInternalNotes(complaintId: string): InternalNote[] {
    return this.db.internalNotes.filter((n) => n.complaintId === complaintId);
  }
  public addInternalNote(note: Omit<InternalNote, 'id' | 'createdAt'>): InternalNote {
    const newNote: InternalNote = {
      ...note,
      id: `note-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
      createdAt: new Date().toISOString(),
    };
    this.db.internalNotes.push(newNote);
    this.saveDatabase();
    return newNote;
  }

  // Clarifications
  public getClarifications(complaintId: string): StudentClarification[] {
    return this.db.clarifications.filter((c) => c.complaintId === complaintId);
  }
  public addClarificationRequest(
    complaintId: string,
    requestedByStaffId: string,
    requestedByName: string,
    requestText: string
  ): StudentClarification {
    const clarification: StudentClarification = {
      id: `clar-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
      complaintId,
      requestedByStaffId,
      requestedByName,
      requestText,
      requestedAt: new Date().toISOString(),
    };
    this.db.clarifications.push(clarification);
    this.saveDatabase();
    return clarification;
  }
  public answerClarification(clarificationId: string, responseText: string): StudentClarification | null {
    const idx = this.db.clarifications.findIndex((c) => c.id === clarificationId);
    if (idx === -1) return null;
    this.db.clarifications[idx].responseText = responseText;
    this.db.clarifications[idx].respondedAt = new Date().toISOString();
    this.saveDatabase();
    return this.db.clarifications[idx];
  }

  // Settings
  public getSettings(): SystemSettings {
    return this.db.settings;
  }
  public updateSettings(updates: Partial<SystemSettings>): SystemSettings {
    this.db.settings = { ...this.db.settings, ...updates };
    this.saveDatabase();
    return this.db.settings;
  }
}

export const dbManager = new DatabaseManager();
